// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211110184647_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("Domain.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("daaca8bb-133c-4599-ad25-8bd8147e65c7"),
                            Description = "Tecnología de Microsoft",
                            Name = "Dotnet Core"
                        },
                        new
                        {
                            Id = new Guid("e25ac6b5-a7e4-4cf4-9c4d-65eca21f2ed8"),
                            Description = "Tecnología de Google",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("bc13420d-8ec1-4df7-b1d3-79e5c148939e"),
                            Description = "Tecnología de Facebook",
                            Name = "React"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
